### ISSUE TITLE
prepositions

### ISSUE THREAD

**Issue by eleven-monks** [nicowilliams/accept-auth-and-redirect#2]
https://github.com/nicowilliams/accept-auth-and-redirect/blob/b2f5d2168211bc418297bc1f10221227b1a8b3d0/accept-auth-and-redirect.txt#L143

The Accept-Redirect-Auth request header exists to indicate to which authorities the user-agent is willing to redirect and authenticate.

??

**Comment by nicowilliams** [comment]
IMO this should be up to the RFC-Editor.  My preference is not to view sentence-ending prepositions as problematic.  Consensus on this is not universal.  But if the RFC-Editor wants this changed, I will do so when they ask.
