### ISSUE TITLE
"

### ISSUE THREAD

**Issue by eleven-monks** [nicowilliams/accept-auth-and-redirect#5]
https://github.com/nicowilliams/accept-auth-and-redirect/blob/b2f5d2168211bc418297bc1f10221227b1a8b3d0/accept-auth-and-redirect.txt#L197

**Comment by eleven-monks** [comment]
"such" -> "Such"

**Comment by eleven-monks** [comment]
or perhaps "These"?

**Comment by nicowilliams** [comment]
Will fix.

**Comment by nicowilliams** [comment]
Fixed.
